### PR TITLE
Revamp Minitracer

### PR DESCRIPTION
**Pull request by Derpius**
* Fix camera calcs
* Add vertical field of view parameter
* Move `runOnTick` to `if (first())`
* Replace deprecated `changed()` with `~` (and check if the wirelink is actually wired)
* Remove unused directives
* Add `@strict`
* Remove `propSpawnUndo(0)` (it wasn't even using propcore functions so I assume this is a copy paste error)
* Remove unused `SUN` vector
* Clean up formatting
* Update invalid comment in `initScreen`

### CODE REVIEW

**Comment by Fasteroid** [comment]
> * Update invalid comment in `initScreen`

Not quite sure what you mean by this, I see no changes to any comments aside from minor formatting changes.

Besides that everything else looks great; I'll probably merge this.

**Comment by Derpius** [comment]
The comment said colour mode 3, but you're using colour mode 2
https://github.com/Fasteroid/expression2-public/pull/3/commits/71a1204644268e570f8a742f1123d476723f2bf5#diff-55b2da8f35ac8c528c5031be5060e35587f9dd8a0e0b38cf9e475c31b611fa24L17

**Comment by Fasteroid** [comment]
> The comment said colour mode 3, but you're using colour mode 2 [71a1204#diff-55b2da8f35ac8c528c5031be5060e35587f9dd8a0e0b38cf9e475c31b611fa24L17](https://github.com/Fasteroid/expression2-public/commit/71a1204644268e570f8a742f1123d476723f2bf5#diff-55b2da8f35ac8c528c5031be5060e35587f9dd8a0e0b38cf9e475c31b611fa24L17)

nevermind, good catch.

**Comment by Fasteroid** [comment]
Whether through my fault or yours, this PR still left additional bugs to address.

**Pull request merged**
